FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development

# Install deps (use npm install to be tolerant if no lockfile present)
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN npm install --silent

# Copy source
COPY . .

EXPOSE 5173

CMD ["npm","run","dev","--","--host","0.0.0.0"]
